/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'
import { Route as ApiWebhookPackagesRouteImport } from './routes/api/webhook.packages'
import { Route as ApiCalendarEventsRouteImport } from './routes/api/calendar.events'

const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookPackagesRoute = ApiWebhookPackagesRouteImport.update({
  id: '/api/webhook/packages',
  path: '/api/webhook/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarEventsRoute = ApiCalendarEventsRouteImport.update({
  id: '/api/calendar/events',
  path: '/api/calendar/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/packages': typeof PackagesRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/webhook/packages': typeof ApiWebhookPackagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/packages': typeof PackagesRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/webhook/packages': typeof ApiWebhookPackagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/packages': typeof PackagesRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/webhook/packages': typeof ApiWebhookPackagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/packages'
    | '/api/subscribe'
    | '/api/calendar/events'
    | '/api/webhook/packages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/packages'
    | '/api/subscribe'
    | '/api/calendar/events'
    | '/api/webhook/packages'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/packages'
    | '/api/subscribe'
    | '/api/calendar/events'
    | '/api/webhook/packages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  PackagesRoute: typeof PackagesRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
  ApiCalendarEventsRoute: typeof ApiCalendarEventsRoute
  ApiWebhookPackagesRoute: typeof ApiWebhookPackagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/packages': {
      id: '/api/webhook/packages'
      path: '/api/webhook/packages'
      fullPath: '/api/webhook/packages'
      preLoaderRoute: typeof ApiWebhookPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/events': {
      id: '/api/calendar/events'
      path: '/api/calendar/events'
      fullPath: '/api/calendar/events'
      preLoaderRoute: typeof ApiCalendarEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  PackagesRoute: PackagesRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
  ApiCalendarEventsRoute: ApiCalendarEventsRoute,
  ApiWebhookPackagesRoute: ApiWebhookPackagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
